---
cache:
  directories:
    - ./client/Carthage

matrix:
  include:
  - name: "Succinct Unit Tests"
    language: swift
    osx_image: xcode10
    xcode_project: Succinct.xcodeproj
    xcode_scheme: Succinct
    xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone 7
    install:
      - carthage bootstrap --platform iOS --cache-builds

  - name: "Succinct Simulator Tests"
    language: swift
    osx_image: xcode10
    xcode_project: Succinct.xcodeproj
    xcode_scheme: SuccinctContainer
    xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone 7
    install:
      - carthage bootstrap --platform iOS --cache-builds
